### ISSUE TITLE
mathscr letters show in mathcal in 0.3.7

### ISSUE THREAD

**Issue by rzach** [vlmantova/bookml#11]
I switched to 0.3.7 from 0.3.6 and now all my `\mathscr` characters display as `\mathcal`

I'm not sure if this is a problem in my source (maybe I should explicitly use `\mathscr`) or in BookML, or in MathJax (doesn't honor `mathvariant="script"`).

The source MathML produced by both versions (ie by LatexML) is this:
```
<math id="S2.p4.m1" class="ltx_Math" alttext="\mathcal{A}" display="inline"><mi class="ltx_font_mathcaligraphic">𝒜</mi></math>
```
The MathJax MathML in 0.3.7 is 
```
<math xmlns="http://www.w3.org/1998/Math/MathML" id="S2.p4.m1" alttext="\mathcal{A}" display="inline" class="ltx_Math">
  <mi data-mjx-variant="-tex-calligraphic" mathvariant="script" class="ltx_font_mathcaligraphic">A</mi>
</math>
```
with 0.3.6 it was
```
<math xmlns="http://www.w3.org/1998/Math/MathML" id="S2.p4.m1" alttext="\mathcal{A}" display="inline" class="ltx_Math">
  <mi class="ltx_font_mathcaligraphic">&#x1D49C;</mi>
</math>
```

**Comment by rzach** [comment]
Oh I think I see what's going on. LatexML converts `\mathcal` to script unicode letters (probably because I use `\usepackage[cal=boondoxo]{mathalfa}`). You wanted `\mathcal` to actually show in the `\mathcal` font but can't tell that I intended script letters?

**Comment by rzach** [comment]
I switched to using `\mathscr` and it shows the script letters again. So it's fixed/wasn't a BookML issue; but note that BookML will probably not show script letters in some cases where it's expected.

**Comment by xworld21** [comment]
Incredible timing: I spotted the same problem this morning. Some packages use `\mathcal` to output roundhand style characters, but LaTeXML uses the same `\mathcal` implementation in most places. Since BookML now is able to output chancery characters when appropriately tagged by LaTeXML, you get the wrong output whenever LaTeXML is using the wrong `\mathcal`. I'll report the issue to LaTeXML as related to the `mathalpha` binding.
