### ISSUE TITLE
Wrong whitespace for numbered listing using gitbook style

### ISSUE THREAD

**Issue by schmitts** [vlmantova/bookml#25]
I'm using `v0.10.2` with LaTeXML version `0.8.8` using the default `gitbook` style.

I'm having a problem with numbered listings.

In the following example are two listings. The first is without line numbers. The second has line numbers on the left.

```latex
\documentclass{article}
\usepackage{listings}

\begin{document}

Without line numbers:

\begin{lstlisting}
#include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
\end{lstlisting}

With line numbers:

\begin{lstlisting}[numbers=left]
#include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
\end{lstlisting}

\end{document}
```

The one without line numbers renders as expected. But the version with line numbers shows wrong whitespace:

![grafik](https://github.com/user-attachments/assets/ead738b9-d22a-47d8-8201-34404bbe5c19)

I tracked the problem down to the lines following https://github.com/vlmantova/bookml/blob/main/CSS/style.gitbook.scss#L390. When I remove them, both listings, with and without line numbers, render as expected.

The problem shows in Firefox 131.0.3 and Chrome 130.0.6723.69, both under Fedora 40.

Thanks!

**Comment by xworld21** [comment]
Fantastic bug report, thank you. This might be due to LaTeXML changing stylesheet slightly in 0.8.8. Now I just need to remember if there were any *other* reasons for setting `white-space: normal`...

Temporary workaround is to add a file, say `bmluser/style.gitbook.css`, with a copy of the same CSS lines with values that fix your particular issue. I'll release an update when I am confident I am not breaking something else.

**Comment by sschmittsva** [comment]
Thanks for the fix! Here is what I put together with bookml: https://xv6-guide.github.io/xv6-riscv-book/.
